name: "Publish Operator"

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:

jobs:
  publish:
    name: Publish container images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Unshallow 
        run: git fetch --prune --unshallow --tags  

      - name: Set env vars for the job
        run: |
          grep -v '\#' versions.txt | grep newrelic-instrumentation-java | awk -F= '{print "NEWRELIC_INSTRUMENTATION_JAVA_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep newrelic-instrumentation-nodejs | awk -F= '{print "NEWRELIC_INSTRUMENTATION_NODEJS_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep newrelic-instrumentation-python | awk -F= '{print "NEWRELIC_INSTRUMENTATION_PYTHON_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep newrelic-instrumentation-dotnet | awk -F= '{print "NEWRELIC_INSTRUMENTATION_DOTNET_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep newrelic-instrumentation-php | awk -F= '{print "NEWRELIC_INSTRUMENTATION_PHP_VERSION="$2}' >> $GITHUB_ENV
          echo "VERSION_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/newrelic-agent-operator/newrelic-agent-operator
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{raw}}
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Operator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION_PKG=github.com/${{ github.repository_owner }}/newrelic-agent-operator/internal/version
            VERSION=${{ env.VERSION }}
            VERSION_DATE=${{ env.VERSION_DATE }}
            NEWRELIC_INSTRUMENTATION_JAVA_VERSION=${{ env.NEWRELIC_INSTRUMENTATION_JAVA_VERSION }}
            NEWRELIC_INSTRUMENTATION_NODEJS_VERSION=${{ env.NEWRELIC_INSTRUMENTATION_NODEJS_VERSION }}
            NEWRELIC_INSTRUMENTATION_PYTHON_VERSION=${{ env.NEWRELIC_INSTRUMENTATION_PYTHON_VERSION }}
            NEWRELIC_INSTRUMENTATION_DOTNET_VERSION=${{ env.NEWRELIC_INSTRUMENTATION_DOTNET_VERSION }}
            NEWRELIC_INSTRUMENTATION_PHP_VERSION=${{ env.NEWRELIC_INSTRUMENTATION_PHP_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
